server:
  port: ${PORT:9095}
spring:
  profiles:
    active: myschool-mysql
  jpa:
    hibernate:
      ddl-auto: update

myschool:
  contact:
    email: ENC(juW91U3lr0feLS/oUFqlR+BlWkfPWhIH5M9AZuJTPf8=)
    phone:
  jwtSecret:  hamarasecret
  jwtExpirationMs:  86400000
  security:
    enabled: true
  root-dir: .
  contactUsFile: Contacted_Us.json

jasypt:
  encryptor:
    password: ==1k1kc-ur-a55==
    algorithm: PBEWithSHA1AndRC2_128
    keyObtentionIterations: 1000
    poolSize: 1
    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator
    stringOutputType: base64
    proxyPropertySources: false

logging:
  level:
    root: info
    com.myschool: debug
  file:
    path: ${project.build.directory}/logs/
    name: myschool-adminservice.log
    config: classpath:logback-spring.xml
  #  pattern.level: "%-50mdc{operationId:-no operationId} %5p"
  #postgresql-fluffy-79708
---

spring:
  profiles: myschool-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/myschool_admin?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: password1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: info
    com.myschool: debug
---

spring:
  profiles: myschool-postgres
  datasource:
    url: jdbc:postgresql://ec2-3-214-4-151.compute-1.amazonaws.com:5432/dct0h1lf0cpk7v?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: ypddwpsogxnuyx
    password: 9e4f28ff719aa130fd8a5760173889d5f0a059e97840be372ea41c31efc31cd4
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

---

spring:
  profiles: myschool-localpostgres
  datasource:
    url: jdbc:postgresql://localhost:5432/rahul.ganta?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username:
    password:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

---